version: "3.9" # opsiyonel.

services:

  frontend:
    # container_name: frontend # (default:key)
    image: stock-app/frontend:latest # image_name
    build: ./frontend # The folder to be dockerized (dockerfile)
    ports: # external/internal port numbers
      - 3000:3000
    depends_on: # run the following first
      - backend # defined below.

  backend:
    # container_name: backend # (default:key)
    image: stock-app/backend:latest # image_name
    build: ./backend # The folder to be dockerized (dockerfile)
    ports: # external/internal port numbers
      - 8000:8000
    env_file:
      - ./backend/.env   
    # volumes: # physical ways (external:internal)
    #   - ./backend:/backend
    #   - $PWD/backend/db.sqlite3:/backend/db.sqlite3

# $ docker compose up
# $ docker compose up -d --build
# $ docker compose down